### ISSUE TITLE
Unable to make Focus Crystal

### ISSUE THREAD

**Issue by Johannason** [Ender-Development/Aetherworks-Extended-Life#5] opened 2024-12-19 03:34 UTC
I'm running Embers UEL, Soot UEL, and Aetherworks UEL, and was working on building the aetherium collection structure.
The recipe for the focus crystal didn't work.
It's an Ember Shard in a Stamper with a Flat Stamp, while the Stamper contains 1b of water.
However there is another recipe where an Ember Shard in a Stamper with a Flat Stamp pounds the shard into Ember Grit.
So I got Grit every time, whether the Stamp Base was full of water or only had exactly the 1b required.

**Comment by MasterEnderman** [comment] 2024-12-19 04:53
Great finding! Probably caused by the original embers aetherworks deepened on (not the rekindled version) didn't have this recipe. Will be fixed asap.

**Closed as completed** 2024-12-19 12:13 UTC
Labels: bug
